### ISSUE TITLE
AshJason.Extension does not trigger when in use with AshJson API

### ISSUE THREAD

**Issue by briankariuki** [vonagam/ash_jason#1]
I wanted to exclude some attributes from my user resource. I added this extension but it is not being triggered. 

Here is my jason section in the user's resource

```
 jason do
    # pick %{sensitive?: false}
    # pick %{private?: false}
    # pick %{exclude: [:hashed_password]}

    customize fn result, _record ->
      IO.inspect(result) //Expect this line to be triggered and print to console
      # result |> Map.put(:custom_key, "custom_value")
      result
    end
  end
```

and the json api section 
```
json_api do
    type "User"

    routes do
      base "/user"

      get :read
    end
  end
```

**Comment by vonagam** [comment]
`AshJsonApi` does not call `Jason.encode` directly on a resource so it does not use `Jason.Encoder` implementation. It converts resource record to a map following its own rules and then encodes that map.

If you use `AshJsonApi` you most likely do not need `AshJason`. `AshJason` is when you do your own thing (with controllers or live views) and not relevant when you use apis like `AshJsonApi` or `AshGraphql`.

Hope it helps.

**Comment by briankariuki** [comment]
Thanks for the clarification
